import { describe, it, expect, vi, afterEach } from 'vitest';
import type { FetchproxyServer, FetchproxyServerOpts } from '@chrischall/mcp-utils/fetchproxy';
import { OneHomeClient } from '../src/client.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';
import { DirectTransport } from '../src/transport-direct.js';
import { FetchproxyTransport } from '../src/transport-fetchproxy.js';
import { createTestHarness } from './helpers.js';

/**
 * A CloudFront WAF block is not a rejected token (chrischall/mcp-host#1015).
 *
 * Both transports read ANY 401/403 from services.onehome.com as "rejected the
 * token" and dropped the page: the direct transport told the user to refresh
 * ONEHOME_TOKEN / ONEHOME_MAGIC_LINK, the capture transport threw its captured
 * bearer away, and onehome_healthcheck repeated the refresh-the-token advice.
 * A CDN refusal never reached the API, so none of that was true.
 *
 * These run the REAL transports against the page CloudFront serves.
 */

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  'Request blocked. We can\'t connect to the server for this app or website at this time. ' +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

function blocked(): Response {
  return new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    statusText: 'Forbidden',
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront', server: 'CloudFront' },
  });
}

function json(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

const FAKE_JWT_BODY = Buffer.from(JSON.stringify({ exp: 1900000000 })).toString('base64url');
const FAKE_JWT = `eyJhbGciOiJIUzI1NiJ9.${FAKE_JWT_BODY}.sig`;

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint: string;
}

let harness: Awaited<ReturnType<typeof createTestHarness>> | undefined;
afterEach(async () => {
  if (harness) {
    await harness.close();
    harness = undefined;
  }
});

async function healthcheck(client: OneHomeClient): Promise<Result> {
  harness = await createTestHarness((server) => registerHealthcheckTools(server, client));
  const r = await harness.callTool('onehome_healthcheck', {});
  const first = r.content[0]!;
  if (first.type !== 'text') throw new Error('expected text');
  return JSON.parse(first.text) as Result;
}

/** A bridge whose header capture always yields `Bearer <jwt>`, counting captures. */
function captureTransport(fetchImpl: typeof fetch): { transport: FetchproxyTransport; captures: () => number } {
  let captures = 0;
  const createServer = (_opts: FetchproxyServerOpts): FetchproxyServer =>
    ({
      role: 'mock',
      async listen(): Promise<void> {},
      async close(): Promise<void> {},
      async captureRequestHeader(): Promise<string> {
        captures += 1;
        return `Bearer ${FAKE_JWT}`;
      },
      bridgeHealth: () => ({
        role: 'mock',
        port: 0,
        serverVersion: 'test',
        fetchTimeoutMs: 0,
        bridgeReviveDelayMs: 0,
        lastSuccessAt: null,
        lastFailureAt: null,
        lastFailureReason: null,
        consecutiveFailures: 0,
        lastExtensionMessageAt: null,
      }),
    }) as unknown as FetchproxyServer;
  return {
    transport: new FetchproxyTransport({ version: '0.0.0-test', fetchImpl, createServer }),
    captures: () => captures,
  };
}

describe('a CloudFront block reads as edge_blocked, not a rejected token', () => {
  it('healthcheck, direct transport (ONEHOME_TOKEN)', async () => {
    const fetchImpl = vi.fn(async () => blocked());
    const transport = new DirectTransport({
      token: FAKE_JWT,
      authMode: 'env_token',
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    const r = await healthcheck(new OneHomeClient({ transport }));

    expect(fetchImpl).toHaveBeenCalled();
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.message).toMatch(/CloudFront/);
    expect(r.error?.message).not.toMatch(/rejected the token/);
    expect(r.hint).not.toMatch(/Refresh ONEHOME_TOKEN/);
    expect(r.hint).toMatch(/CDN\/WAF/);
  });

  it('healthcheck, direct transport, on the magic-link token exchange', async () => {
    const fetchImpl = vi.fn(async () => blocked());
    const transport = new DirectTransport({
      // Not JWT-shaped, so the transport exchanges it at checkToken first.
      token: 'opaque-email-token',
      authMode: 'magic_link',
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    const r = await healthcheck(new OneHomeClient({ transport }));

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).not.toMatch(/Refresh ONEHOME_TOKEN|resend the magic link/);
  });

  it('capture transport: a blocked GraphQL call keeps the captured token', async () => {
    let block = true;
    const fetchImpl = vi.fn(async () => (block ? blocked() : json(200, { data: { user: { userId: 'u1' } } })));
    const { transport, captures } = captureTransport(fetchImpl as unknown as typeof fetch);

    const err = await transport
      .graphql({ operationName: 'GetOneHomeUser', query: '{ user { userId } }' })
      .catch((e: unknown) => e);
    expect((err as Error).name).toBe('EdgeBlockedError');
    expect((err as Error).message).not.toMatch(/rejected the captured token/);

    block = false;
    await transport.graphql({ operationName: 'GetOneHomeUser', query: '{ user { userId } }' });
    // No recapture: the block said nothing about the token.
    expect(captures()).toBe(1);
  });

  it('capture transport: a blocked REST call keeps the captured token', async () => {
    const fetchImpl = vi.fn(async () => blocked());
    const { transport, captures } = captureTransport(fetchImpl as unknown as typeof fetch);

    const res = await transport.rest('/schools?lat=1&lng=2');

    expect(res.ok).toBe(false);
    expect(res.status).toBe(403);
    // Neither dropped nor re-fetched on a recapture.
    expect(captures()).toBe(1);
    expect(fetchImpl).toHaveBeenCalledTimes(1);
  });

  it("control: the API's own 401 is still a rejected token", async () => {
    const fetchImpl = vi.fn(async () => json(401, { message: 'Unauthorized' }));
    const transport = new DirectTransport({
      token: FAKE_JWT,
      authMode: 'env_token',
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    const r = await healthcheck(new OneHomeClient({ transport }));

    expect(r.error?.kind).not.toBe('edge_blocked');
    expect(r.error?.message).toMatch(/rejected the token \(HTTP 401\)/);
    expect(r.hint).toMatch(/Refresh ONEHOME_TOKEN/);
  });
});
